language: cpp

sudo: required

dist: trusty

cache:
  apt: true

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug CODECOV=ON COMPILER=GCC
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release CODECOV=OFF COMPILER=GCC
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Debug CODECOV=OFF COMPILER=CLANG
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Release CODECOV=OFF COMPILER=CLANG

install:
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  - brew

#script:
#  - 
