language: cpp

sudo: required

dist: trusty

cache:
  apt: true

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug CODECOV=ON COMPILER=GCC
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release CODECOV=OFF COMPILER=GCC
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Debug CODECOV=OFF COMPILER=CLANG
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Release CODECOV=OFF COMPILER=CLANG

install:
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  - echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' >>~/.profile
  - echo 'export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"' >>~/.profile
  - echo 'export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"' >>~/.profile
  - PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
  - brew --version
  #- brew doctor
  - brew update > /dev/null
  - brew install cmake
  - brew info dartsim

#script:
#  - mkdir build && cd build
#  - cmake ..
